# ==============================================================================
# Custom Keybindings & Shortcuts (Пользовательские горячие клавиши)
# ==============================================================================
# $mainMod is SUPER (Mod4)
# Examples:
# bind = $mainMod, C, exec, code
# bind = $mainMod, B, exec, brave
# bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod SHIFT, H, exec, qs -c $HOME/.config/panacea ipc call pill homelab
